name: 'PR ls-files action'
description: 'pull_request ls-files action'
author: srz-zumix

inputs:
  pull_request:
    description: 'pull request number|url|branch'
    default: ${{ github.event.pull_request.html_url }}
    type: string
  added:
    description: 'show added files in the output'
    required: false
    default: true
    type: boolean
  deleted:
    description: 'show deleted files in the output'
    required: false
    default: true
    type: boolean
  modified:
    description: 'show modified files in the output'
    required: false
    default: true
    type: boolean
  filter:
    description: 'show files with the specified grep filter in the output'
    required: false
    default: ''
    type: string
  delimiter:
    description: 'delimiter for the output'
    required: false
    default: ""
    type: string
  github_token:
    description: 'GitHub TOKEN'
    default: ${{ github.token }}
    required: false
    type: string

outputs:
  files:
    description: 'files in the pull request'
    value: ${{ steps.ls-files.outputs.files }}
  count:
    description: 'count of files in the pull request'
    value: ${{ steps.ls-files.outputs.count }}

runs:
  using: composite
  steps:
  - name: ls-files
    id: ls-files
    shell: bash
    env:
      PR_LS_FILES_ADDED: ${{ inputs.added }}
      PR_LS_FILES_DELETED: ${{ inputs.deleted }}
      PR_LS_FILES_MODIFIED: ${{ inputs.modified }}
      INPUTS_GITHUB_TOKEN: ${{ inputs.github_token }}
      INPUTS_DELIMITER: ${{ inputs.delimiter }}
      INPUTS_FILTER: ${{ inputs.filter }}
    run: |
      # ls-files
      # shellcheck disable=SC2046
      export GH_ENTERPRISE_TOKEN="${INPUTS_GITHUB_TOKEN:-${GH_ENTERPRISE_TOKEN:-${{ github.token }}}}"
      export GH_TOKEN="${GH_ENTERPRISE_TOKEN}"
      ${{ github.action_path }}/run-on-actions.sh ${{ inputs.pull_request }}

branding:
  icon: 'file'
  color: 'green'
