name: 'PR ls-files action'
description: 'pull_request ls-files action'
author: srz-zumix

inputs:
  pull_request:
    description: 'pull request number|url|branch'
    default: ${{ github.event.pull_request.html_url }}
    type: string
  repository:
    description: 'repository'
    default: ${{ github.repository }}
    type: string
  added:
    description: 'show added files in the output'
    type: string
  deleted:
    description: 'show deleted files in the output'
    type: string
  modified:
    description: 'show modified files in the output'
    type: string
  renamed:
    description: 'show renamed files in the output'
    type: string
  filter:
    description: 'show files with the specified grep filter in the output'
    required: false
    default: ''
    type: string
  delimiter:
    description: 'delimiter for the output'
    required: false
    default: ""
    type: string
  github_token:
    description: 'GitHub TOKEN'
    default: ${{ github.token }}
    required: false
    type: string

outputs:
  files:
    description: 'files in the pull request'
    value: ${{ steps.ls-files.outputs.files }}
  count:
    description: 'count of files in the pull request'
    value: ${{ steps.ls-files.outputs.count }}

runs:
  using: composite
  steps:
  - name: select other flags
    shell: bash
    id: other
    env:
      PR_LS_FILES_ADDED: ${{ inputs.added }}
      PR_LS_FILES_DELETED: ${{ inputs.deleted }}
      PR_LS_FILES_MODIFIED: ${{ inputs.modified }}
      PR_LS_FILES_RENAMED: ${{ inputs.renamed }}
    run: |
      # select other flags
      JOIN_FLAGS=$(
      {
        echo "${PR_LS_FILES_ADDED}"
        echo "${PR_LS_FILES_DELETED}"
        echo "${PR_LS_FILES_MODIFIED}"
        echo "${PR_LS_FILES_RENAMED}"
      } | sort | uniq | tr -d '\n')
      if [ "${JOIN_FLAGS}" = true ]; then
        echo "flag=false" >> "${GITHUB_OUTPUT}"
      else
        echo "flag=true"  >> "${GITHUB_OUTPUT}"
      fi
  - name: ls-files
    id: ls-files
    shell: bash
    env:
      PR_LS_FILES_ADDED: ${{ inputs.added || steps.other.outputs.flag }}
      PR_LS_FILES_DELETED: ${{ inputs.deleted || steps.other.outputs.flag  }}
      PR_LS_FILES_MODIFIED: ${{ inputs.modified || steps.other.outputs.flag  }}
      PR_LS_FILES_RENAMED: ${{ inputs.renamed || steps.other.outputs.flag  }}
      INPUTS_GITHUB_TOKEN: ${{ inputs.github_token }}
      INPUTS_DELIMITER: ${{ inputs.delimiter }}
      INPUTS_FILTER: ${{ inputs.filter }}
      INPUTS_REPOSITORY: ${{ inputs.repository || github.repository }}
    run: |
      # ls-files
      # shellcheck disable=SC2046
      export GH_ENTERPRISE_TOKEN="${INPUTS_GITHUB_TOKEN:-${GH_ENTERPRISE_TOKEN:-${{ github.token }}}}"
      export GH_TOKEN="${GH_ENTERPRISE_TOKEN}"
      ${{ github.action_path }}/run-on-actions.sh -R "${INPUTS_REPOSITORY}" ${{ inputs.pull_request }}

branding:
  icon: 'file'
  color: 'green'
