name: 'PR ls-files action'
description: 'pull_request ls-files action'
author: srz-zumix

inputs:
  pull_request:
    description: 'pull request number|url|branch'
    default: ${{ github.event.number }}
    type: string
  added:
    description: 'show added files in the output'
    required: false
    default: true
    type: boolean
  deleted:
    description: 'show deleted files in the output'
    required: false
    default: true
    type: boolean
  modified:
    description: 'show modified files in the output'
    required: false
    default: true
    type: boolean
  github_token:
    description: 'GitHub TOKEN'
    default: ${{ github.token }}
    required: false
    type: string

outputs:
  files:
    description: 'files in the pull request'
    value: ${{ steps.ls-files.outputs.files }}
    type: string

runs:
  using: composite
  steps:
  - name: ls-files
    id: ls-files
    shell: bash
    env:
      PR_LS_FILES_ADDED: ${{ inputs.added }}
      PR_LS_FILES_DELETED: ${{ inputs.deleted }}
      PR_LS_FILES_MODIFIED: ${{ inputs.modified }}
      INPUTS_GITHUB_TOKEN: ${{ inputs.github_token }}
    run: |
      # shellcheck disable=SC2046
      export GH_ENTERPRISE_TOKEN="${INPUTS_GITHUB_TOKEN:-${GH_ENTERPRISE_TOKEN:-${{ github.token }}}}"
      export GH_TOKEN="${GH_ENTERPRISE_TOKEN}"
      DELIMITER="<$(openssl rand -hex 8)>"
      {
        echo "files<<${DELIMITER}"
        ${{ github.action_path }}/gh-pr-ls-files ${{ inputs.pull_request }}
        echo "${DELIMITER}"
      } >> "${GITHUB_OUTPUT}"

branding:
  icon: 'file'
  color: 'green'
